# Generated by Django 3.0 on 2020-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200122_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=32)),
                ('join_year', models.IntegerField()),
                ('is_senior', models.BooleanField()),
                ('was_kore', models.BooleanField()),
                ('is_kore', models.BooleanField()),
                ('image', models.ImageField(upload_to='members/')),
            ],
        ),
    ]
